config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :dashboard, only: :index

  resources :decks, only: [:show, :new, :create, :update, :destroy] do
    resources :questions, only: [:index, :new, :create, :show, :update, :destroy], controller: 'decks/questions'
    resources :study, only: [:index, :update], controller: 'decks/study'
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @decks = current_user.decks.order(:created_at).page(params[:page])
  end
end

app/views/dashboard/index.html.erb
<div class="container mx-auto py-16" data-controller="deck">
  <% if @decks.empty? %>
    <h3> You don't have any decks yet. Create one and start to study! </h3>
  <% else %>
    <ul role="list" class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-4 sm:gap-x-6 lg:grid-cols-5 xl:gap-x-8">
      <% @decks.each do |deck| %>
        <li class="relative shadow-lg bg-white ">
          <div class="group block w-full aspect-w-10 aspect-h-7 rounded-t-lg bg-gray-100 overflow-hidden pointer-events-none ">
             <%= image_tag default_image(deck), class: 'object-cover' %> 
            <button type="button" class="absolute inset-0 focus:outline-none">
              <span class="sr-only">View details for IMG_4985.HEIC</span>
            </button>
          </div>
          <div class="p-6">
            <h5 class="text-gray-900 text-xl font-medium mb-2 underline"><%= deck.name %></h5>
            <p class="block text-sm font-medium text-gray-500 "> <%= deck.description.truncate(14, omission: '')%>
              <% if deck.description.length > 14 %>
                <%= link_to "...", "", class: "text-lg font-medium underline text-blue-700 hover:text-black", data: {action: "deck#openDeckDescriptionModal", 'deck-id-param':"12345" } %>
                <% render "decks/description" %>
              <% end %>
            </p>
            <p class="block text-sm font-medium text-gray-500 pointer-events-none">Retention rate: <%= deck.retention_spectrum %>%</p>
            <p class="block text-sm font-medium text-gray-500 pointer-events-none">Correct rate: <%= deck.correct_times_rate %>%</p>
            <p class="block text-sm font-medium text-gray-500 pointer-events-none">Questions done: <%= deck.questions_times_done %></p>
            <p class="block text-sm font-medium text-gray-500 pointer-events-none mb-3">Cards: <%= deck.questions.count %></p>
            <%= link_to "Edit", deck_path(deck),
              class: 'inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out'
            %>
            <%= link_to "Study", deck_study_index_path(deck),
              class: 'inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out'
            %>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>
<%= paginate @decks %>