config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :dashboard, only: :index

  resources :decks, only: [:show, :new, :create, :update, :destroy] do
    resources :questions, only: [:index, :new, :create, :show, :update, :destroy], controller: 'decks/questions'
    resources :study, only: [:index, :update], controller: 'decks/study'
  end

end

app/models/deck.rb
class Deck < ApplicationRecord
  paginates_per 10

  belongs_to :user

  has_many :questions, dependent: :destroy

  has_one_attached :deck_image, dependent: :destroy

  validates :name, length: { maximum: 13 }, presence: true
  validates :description, presence: true
end

app/controllers/decks/questions_controller.rb
module Decks
  class QuestionsController < ApplicationController
    before_action :authenticate_user!

    def index
      @questions = Deck.find(params[:deck_id]).questions.order(:created_at).page(params[:page])
    end

    def new
      @question = Question.new
    end

    def create
      @question = Deck.find(params[:deck_id]).questions.create(question_params)

      if @question.save
        redirect_to deck_questions_path(params[:deck_id])
      else
        head :unprocessable_entity
      end
    end

    def show
      @question = Question.find(params[:id])
    end

    def update
      @question = Question.find(params[:id])
      if @question.update(question_params)
        redirect_to deck_question_path(params[:deck_id])
      else
        head :unprocessable_entity
      end
    end

    def destroy; end

    private

    def question_params
      params.permit(:question, :correct_answer, :question_type, :wrong_answer_n1, :wrong_answer_n2, :wrong_answer_n3)
    end
  end
end

app/controllers/decks/study_controller.rb
module Decks
  class StudyController < ApplicationController
    before_action :authenticate_user!

    def index
       if quesiton_empty?
        redirect_to deck_questions_path
      else
        question_to_study
      end
    end

    def update
      @question_data = Question.find(params[:id]).question_data
      @question_data.update_data(params[:question][:correct_answer])
      redirect_to deck_study_index_path(params[:deck_id])
    end

    private

    def quesiton_empty?
      Deck.find(params[:deck_id]).questions.empty?
    end
    
    def question_to_study
      @question = Deck.find(params[:deck_id]).questions.to_study
    end
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!

  def show
    @deck = Deck.find(params[:id])
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = current_user.decks.new(deck_params)

    if @deck.save
      redirect_to dashboard_index_path
    else
      render :new
    end
  end

  def update
    @deck = Deck.find(params[:id])
    @deck.update(deck_params)
  end

  def destroy
    deck = Deck.find(params[:id])
    deck.destroy
    redirect_to dashboard_index_path
  end

  private

  def deck_params
    params.require(:deck).permit(:name, :description, :deck_image)
  end
end

app/helpers/deck_helper.rb
module DeckHelper
  def default_image(deck)
    deck.deck_image.presence || 'https://images.unsplash.com/photo-1582053433976-25c00369fc93?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=512&q=80'
  end
end

app/views/decks/study/_multiple_choice.html.erb
<div class="h-full bg-gray-100" data-controller="study" >
  <main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
    <div class="lg:grid lg:grid-cols-12 lg:gap-x-10">
      <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-12">
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
            <div class="shadow sm:rounded-md sm:overflow-hidden border" data-study-target="panel">
              <div class="bg-white py-6 px-4 space-y-6 sm:p-6 " >
                <div class="grid grid-cols-6 gap-6 " data-study-target="render">
                  <div class="col-span-6">
                    <h3 class="text-lg leading-6 font-medium text-gray-900">Choose the correct answer <span class="mt-1 text-sm text-gray-500">One of those are correct! Only one!</span></h3>
                    
                  </div>
                  <div class="col-span-6">
                    <h3 class="text-center text-lg leading-6 font-medium text-gray-900"><%= @question.question %></h3>
                  </div>

                  <% shuffled_questions = @question.attributes.select { |k, v|  k == "correct_answer" || k.include?("wrong") }.values.shuffle %>

                  <div class="col-span-6 sm:col-span-3">
                    <%= text_area_tag shuffled_questions[0], shuffled_questions[0], class: "hover:cursor-pointer hover:bg-gray-200 mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:bg-blue-100 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm",
                      'data-study-target':'inputField',
                      readonly: true %>
                  </div>


                  <div class="col-span-6 sm:col-span-3">
                    <%= text_area_tag shuffled_questions[1], shuffled_questions[1], class: "hover:cursor-pointer hover:bg-gray-200 mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:bg-blue-100 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm",
                      'data-study-target':'inputField',
                      readonly: true %>
                  </div>

                  <div class="col-span-6 sm:col-span-3 red">
                    <%= text_area_tag shuffled_questions[2], shuffled_questions[2], class: "hover:cursor-pointer hover:bg-gray-200 mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:bg-blue-100 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm",
                      'data-study-target':'inputField',
                      readonly: true %>
                  </div>

                  <div class="col-span-6 sm:col-span-3">
                    <%= text_area_tag shuffled_questions[3], shuffled_questions[3], class: "hover:cursor-pointer hover:bg-gray-200 mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:bg-blue-100 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm",
                      'data-study-target':'inputField',
                      readonly: true %>
                  </div>

                  <div class="col-span-6 text-right">
                    <%= form_with model: @question, url: deck_study_path(@question.deck.id, @question.id), local: true,  html: {'data-study-target':'form'} do |x| %>
                      <%= x.text_field 'correct_answer', value: '', class:'hidden', 'data-study-target':'toSubmitField' %>
                      <%= link_to "Exit", root_path,  class:'bg-red-500 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500' %>
                      <%= x.submit "submit", class: 'bg-indigo-600 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500',
                        'data-action':'click->study#check_empty_value',
                        'data-study-target':'submitBtn'
                      %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
              </div>
            </div>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/decks/study/_user_correction.html.erb
<div class="h-full bg-gray-100" data-controller="study--user-correction" >
  <main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
    <div class="lg:grid lg:grid-cols-12 lg:gap-x-10">
      <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-12">
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
            <div class="shadow sm:rounded-md sm:overflow-hidden border">
              <div class="bg-white py-6 px-4 space-y-6 sm:p-6" >
                <div class="grid grid-cols-6 gap-6">

                  <div class="col-span-6 sm:col-span-6">
                    <div class="col-span-6">
                      <h3 class="text-lg leading-6 font-medium text-gray-900">Think about the answer, then turn the card. 
                        After that, ask yourself if you were right and then hit <span class="text-red-500">yes</span> or <span class="text-indigo-500">no</span> buttons according to it</h3>
                    </div>
                      <div class="col-span-6 sm:col-span-3">
                        <%= text_area_tag @question.question, @question.question, class: "hover:cursor-pointer hover:bg-gray-200 mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:bg-blue-100 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm",
                          id: 'questionBox',
                          rows: '10',
                          readonly: true %>
                        <%= text_area_tag @question.correct_answer, @question.correct_answer, class: "hidden hover:cursor-pointer hover:bg-gray-200 mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:bg-blue-100 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm",
                          id: 'answerBox',
                          rows: '10',
                          readonly: true %>
                      </div>
                  </div>
                  <div class="col-span-6">
                    <%= button_tag "turn card",
                        'data-action':'click->study--user-correction#turnCard',
                        class:'bg-indigo-600 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white 
                      hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500'
                     %>
                  </div>
                  <div class="col-span-6 text-right">
                    <%= form_with model: @question, url: deck_study_path(@question.deck.id, @question.id), local: true do |x| %>
                      <%= x.text_field 'correct_answer', value: @question.correct_answer, class:'hidden', 'data-study--user-correction-target':'hiddenTextField' %>
                      <%= button_tag "No",
                        'data-study--user-correction-target':'nobtn',
                        class:'bg-red-500 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white 
                        hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500' %>
                      <%= x.submit "Yes", 'data-study--user-correction-target':'submitBtn',
                        class:'bg-indigo-600 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white 
                        hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500'%>
                    <% end %>
                  </div>
              </div>
            </div>
            <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/decks/study/index.html.erb
<% if @question.question_type == 'multiple_choice' %>
  <%= render 'multiple_choice' %>
<% else %>
  <%= render 'user_correction' %>
<% end %>