config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :dashboard, only: :index

  resources :decks, only: [:show, :new, :create, :update, :destroy] do
    resources :questions, only: [:index, :new, :create, :show, :update, :destroy], controller: 'decks/questions'
    resources :study, only: [:index, :update], controller: 'decks/study'
  end

end

app/models/deck.rb
class Deck < ApplicationRecord
  paginates_per 10

  belongs_to :user

  has_many :questions, dependent: :destroy

  has_one_attached :deck_image, dependent: :destroy

  validates :name, length: { maximum: 13 }, presence: true
  validates :description, presence: true
end

app/controllers/decks/questions_controller.rb
module Decks
  class QuestionsController < ApplicationController
    before_action :authenticate_user!

    def index
      @questions = Deck.find(params[:deck_id]).questions.order(:created_at).page(params[:page])
    end

    def new
      @question = Question.new
    end

    def create
      @question = Deck.find(params[:deck_id]).questions.create(question_params)

      if @question.save
        redirect_to deck_questions_path(params[:deck_id])
      else
        head :unprocessable_entity
      end
    end

    def show
      @question = Question.find(params[:id])
    end

    def update
      @question = Question.find(params[:id])
      if @question.update(question_params)
        redirect_to deck_question_path(params[:deck_id])
      else
        head :unprocessable_entity
      end
    end

    def destroy; end

    private

    def question_params
      params.permit(:question, :correct_answer, :question_type, :wrong_answer_n1, :wrong_answer_n2, :wrong_answer_n3)
    end
  end
end

app/controllers/decks/study_controller.rb
module Decks
  class StudyController < ApplicationController
    before_action :authenticate_user!

    def index
       if quesiton_empty?
        redirect_to deck_questions_path
      else
        question_to_study
      end
    end

    def update
      @question_data = Question.find(params[:id]).question_data
      @question_data.update_data(params[:question][:correct_answer])
      redirect_to deck_study_index_path(params[:deck_id])
    end

    private

    def quesiton_empty?
      Deck.find(params[:deck_id]).questions.empty?
    end
    
    def question_to_study
      @question = Deck.find(params[:deck_id]).questions.to_study
    end
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!

  def show
    @deck = Deck.find(params[:id])
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = current_user.decks.new(deck_params)

    if @deck.save
      redirect_to dashboard_index_path
    else
      render :new
    end
  end

  def update
    @deck = Deck.find(params[:id])
    @deck.update(deck_params)
  end

  def destroy
    deck = Deck.find(params[:id])
    deck.destroy
    redirect_to dashboard_index_path
  end

  private

  def deck_params
    params.require(:deck).permit(:name, :description, :deck_image)
  end
end

app/helpers/deck_helper.rb
module DeckHelper
  def default_image(deck)
    deck.deck_image.presence || 'https://images.unsplash.com/photo-1582053433976-25c00369fc93?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=512&q=80'
  end
end

app/views/decks/_description.html.erb
<h1>
  hello world
</h1>

app/views/decks/_sidebar.html.erb
<aside class="py-6 px-2 sm:px-6 lg:py-0 lg:px-0 lg:col-span-3 profiles-sidebar">
  <nav class="space-y-1">
    <%= link_to deck_path(deck), class:"#{controller_name == "decks" ? 'bg-blue-100' : 'hover:bg-gray-50'} text-gray-900 hover:text-gray-900  group rounded-md px-3 py-2 flex items-center text-sm font-medium text-red" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="text-black flex-shrink-0 -ml-1 mr-3 h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 9.776c.112-.017.227-.026.344-.026h15.812c.117 0 .232.009.344.026m-16.5 0a2.25 2.25 0 00-1.883 2.542l.857 6a2.25 2.25 0 002.227 1.932H19.05a2.25 2.25 0 002.227-1.932l.857-6a2.25 2.25 0 00-1.883-2.542m-16.5 0V6A2.25 2.25 0 016 3.75h3.879a1.5 1.5 0 011.06.44l2.122 2.12a1.5 1.5 0 001.06.44H18A2.25 2.25 0 0120.25 9v.776" />
      </svg>
      <span class="truncate"> Deck </span>
    <% end %>

    <%= link_to deck_questions_path(deck), class:"#{controller_name == "questions" ? 'bg-blue-100' : 'hover:bg-gray-50'} text-gray-900 hover:text-gray-900  group rounded-md px-3 py-2 flex items-center text-sm font-medium text-red" do %>
      <!-- Heroicon name: outline/credit-card -->
      <svg xmlns="http://www.w3.org/2000/svg" class="text-black flex-shrink-0 -ml-1 mr-3 h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 01-2.25 2.25M16.5 7.5V18a2.25 2.25 0 002.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 002.25 2.25h13.5M6 7.5h3v3H6v-3z" />
      </svg>
      <span class="truncate"> Questions </span>
    <% end %>
    <%= button_to deck_path(deck), form: { data: { turbo_confirm: "Are you sure? This action is irreversible" } }, method: :delete, class:"text-gray-900 hover:text-gray-900  group rounded-md px-3 py-2 flex items-center text-sm font-medium" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="text-red-500 flex-shrink-0 -ml-1 mr-3 h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
      </svg>
      <span> Destroy deck</span>
    <% end %>
  </nav>
</aside>

app/views/decks/destroy.html.erb
<div class="h-full bg-gray-100">
  <main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
    <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
      <%= render "sidebar", deck: @deck.id %>

      <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <%= form_with model: @deck, url: deck_path(@deck), local: true do |f| %>
            <div class="shadow sm:rounded-md sm:overflow-hidden">
              <div class="bg-white py-6 px-4 space-y-6 sm:p-6">
                <div>
                  <h3 class="text-lg leading-6 font-medium text-gray-900">Update your Deck</h3>
                  <p class="mt-1 text-sm text-gray-500">Use this form to update your deck attributes.</p>
                </div>

                <div class="grid grid-cols-6 gap-6">
                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :name, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>


                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :description, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_area :description, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :deck_image, "Image", class: "block text-sm font-medium text-gray-700" %>
                    <%= f.file_field :deck_image %>
                  </div>

                </div>
              </div>
              <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                <button type="submit" class="bg-indigo-600 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Save</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/decks/new.html.erb
<div class="h-full bg-gray-100">
  <main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
    <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">

      <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <%= form_with model: @deck, url: decks_path, local: true do |f| %>
            <div class="shadow sm:rounded-md sm:overflow-hidden">
              <div class="bg-white py-6 px-4 space-y-6 sm:p-6">
                <div>
                  <h3 class="text-lg leading-6 font-medium text-gray-900">Update your Deck</h3>
                  <p class="mt-1 text-sm text-gray-500">Use this form to update your deck attributes.</p>
                </div>

                <div class="grid grid-cols-6 gap-6">
                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :name, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>


                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :description, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_area :description, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :deck_image, "Image", class: "block text-sm font-medium text-gray-700" %>
                    <%= f.file_field :deck_image %>
                  </div>

                </div>
              </div>
              <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                <button type="submit" class="bg-indigo-600 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Save</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/decks/show.html.erb
<div class="h-full bg-gray-100">
  <main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
    <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
      <%= render "sidebar", deck: @deck.id %>

      <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <%= form_with model: @deck, url: deck_path(@deck), local: true do |f| %>
            <div class="shadow sm:rounded-md sm:overflow-hidden">
              <div class="bg-white py-6 px-4 space-y-6 sm:p-6">
                <div>
                  <h3 class="text-lg leading-6 font-medium text-gray-900">Update your Deck</h3>
                  <p class="mt-1 text-sm text-gray-500">Use this form to update your deck attributes.</p>
                </div>

                <div class="grid grid-cols-6 gap-6">
                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :name, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>


                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :description, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_area :description, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :deck_image, "Image", class: "block text-sm font-medium text-gray-700" %>
                    <%= f.file_field :deck_image %>
                  </div>

                </div>
              </div>
              <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                <button type="submit" class="bg-indigo-600 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Save</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</div>