config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :dashboard, only: :index

  resources :decks, only: [:show, :new, :create, :update, :destroy] do
    resources :questions, only: [:index, :new, :create, :show, :update, :destroy], controller: 'decks/questions'
    resources :study, only: [:index, :update], controller: 'decks/study'
  end

end

app/views/layouts/_header.html.erb
<nav class="bg-blue-custom border-gray-200 px-2 sm:px-4 py-2.5  dark:bg-gray-900">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="/" class="flex items-center">
        <%= image_tag("logo.svg", :alt => "logo", class: "mr-3 h-6 sm:h-9") %>
        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">QuizLearn - flash card app</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "block py-2 pr-4 pl-3 text-gray-700 rounded md:hover:bg-gray-100 md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"%>
          </li>
          <li>
            <%= link_to "Create new deck", new_deck_path, class: "block py-2 pr-4 pl-3 text-gray-700 rounded md:hover:bg-gray-100 md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"%>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "block py-2 pr-4 pl-3 text-gray-700 rounded md:hover:bg-gray-100 md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          </li>
          <li>
            <%= link_to "Log in", new_user_session_path, class: "block py-2 pr-4 pl-3 text-gray-700 rounded md:hover:bg-gray-100 md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashCards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path("logo.svg") %>

  </head>

  <body>
    <%= render "layouts/header" %>
     <%= yield %>
  </body>
</html>